language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"

before_install:
  - sudo apt-get update
  - sudo apt-get install libeigen3-dev
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update conda
  - conda create -n test-environment python=$TRAVIS_PYTHON_VERSION
  - source activate test-environment

install:
  - conda install pip setuptools numpy scipy nose Cython
  - pip install emcee george coveralls nose-cov
  - python setup.py install

script: nosetests --verbose --with-cov --cov mtd

after_success: coveralls
